# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Download Artifact
      uses: actions/download-artifact@v2
    - name: Clean Install
      run: npm ci
    - name: Publish
      run: ./node_modules/vsce/out/vsce --packagePath vscode-vault.vsix --pat $VSCE_PAT
