# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  release:
    types:
      - created

jobs:
  # TODO: Replace this job with an action to retrieve the artifact from the last workflow run
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Clean Install
      run: npm ci
    - name: Run Build
      run: npm run build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: vscode-vault.vsix

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Download Artifact
      uses: actions/download-artifact@v2
    - name: Clean Install
      run: npm ci
    - name: Publish
      # TODO: Remove the --pat flag when vsce support environmental variables
      run: ./node_modules/vsce/out/vsce publish --packagePath ./artifact/vscode-vault.vsix --pat $VSCE_PAT
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
